language: php
php:
    - "5.6"
    - "7.0"
    - "7.1"
    - "nightly"
    - "hhvm"
install:
  - composer self-update
  - composer install --dev
script: vendor/bin/phpunit
addons:
    code_climate:
        repo_token: 3c0e12a373d68ffd090193faf37dbb4f8c3429936d4cab0e8c2cc68c31a412e7
after_success:
  - vendor/bin/test-reporter
sudo: false
